sudo: true
language: java
git:
  depth: 1
services:
- docker
env:
  global:
    secure: dvZEOyZacEHrNEQJA5d8fdFtsTOXQfj/890QTJwa4U2SU5kFSdUDMCgcJoW1lignX8/Fzh4ZPe1eaZlv6/aaf95p4OZVKRFxFW7sdmhNaSx1s84r4tJ04qL3DxjwkfBEW+CIX4FyRpi5e3X4qbbxRtvL9Xnce7rV+9BIigQCxsuUFgMgfxOMXeU6Ob/Tc2Mp4Wb6XJVxB/p6hyT3HNru5H8P/ACVM777UaZj0SbmtpTlwBlKFAU0FZzoBLYqDjANCxBgjc5j4Yaty2tYyltOUuemHkPWNHyhP8WHJHG1n5GmQqvAjRNxYZvelJb26sIuD1NoK2lTLB/BWsPsRNtJIbZ0DvxIfyLI8Md2GfiFy8kSFvahfdjXOdFTBGSdeu2lLNxKWMqiuPtesxHfydI4hrPfXyzhEJvpTpYQWNSaA1IPiAhL8xAZqrEzSsJBj6qSaAQpt0Pu9n97GxiPHwS4OpbhwKCRAyBkcIyLtrUlR5popblbjXmHpkOMnmONFNMCl5fuFH371G8TuMCf5NI1Vr2BHTr+XNMNUhLU2IAeqosLSw1TlwuPI7AXyGioh7WAgQLypwx6SBwCBj1f+thRI5p4Tgb6rMUpgbsETRdtsRJI732K6aB3VB/bI4He/JXaoTZKrmygkKNaj+qtHEJ8EbndQIkmhg6RcBc/vwnifds=
script: bash .travis.sh
